name: oxford_pet
root: data/oxford-iiit-pet

images_dir: images
masks_dir: annotations/trimaps

train_ratio: 0.9
seed: 42

label_mode: species

num_classes: 3
class_names: ["__background__", "cat", "dog"]

image_size: 512